kind: ConfigMap
apiVersion: v1
metadata:
  # Must match the 'spring.application.name' property of the application
  name: ffmeldenbot-config
data:
  application.properties: |
    # Override the configuration properties here
    ffmeldenbot.recipients=direct:async-queue,direct:file,direct:mail