apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "m2repo"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "ff-melden-pipeline"
spec:
  source:
    git:
      uri: $GIT_URI
      ref: $GIT_REF
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile"
      env:
        - name: APP_NAME
          value: "ffmeldenbot"
        - name: GIT_URI
          value: "https://github.com/buuhsmead/ff_melden"
        - name: GIT_REF
          value: "master"

